name: Executar Radar Diário

on:
  schedule:
    - cron: '0 12 * * 1-5' # Roda todo dia útil às 9h da manhã (Brasília)
  workflow_dispatch: # Permite que você rode manualmente pelo site do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: pip install requests pandas

      - name: Rodar Radar
        run: python main.py